#!/usr/bin/env ruby

require_relative 'lib/install_swiftlint'
require_relative 'lib/install_sourcery'
require_relative 'lib/installers'

# Install local binaries in ./bin directory
install_swiftlint
install_sourcery

# Install CI environment dependencies
# proselint is a dependency needed by danger-prose plugin.
pip_install "proselint" if running_on_ci?

# Install Ruby gems
bundle_install

# Install dependencies using Carthage
carthage_bootstrap

puts ""
puts " → You are ready to rock!!!"
puts "\tExecute 'open Portal.xcodeproj' and start hacking!"
puts ""
