#!/usr/bin/env ruby

require_relative 'lib/install_swiftlint'
require_relative 'lib/installers'

install_swiftlint

# Install CI environment dependencies
# proselint is a dependency needed by danger-prose plugin.
pip_install "proselint"

# Install Ruby gems
bundle_install
