#!/bin/bash

set -e
set -x

# Setup development environment
script/bootstrap

# Install CI environment dependencies
# proselint is a dependency needed by danger-prose plugin.
pip install proselint

# Install Ruby gems
bundle install

# Clean artifacts and directories
if [ ! -d ./output ]
then
  mkdir ./output
fi

# Clean, build & test project
set -o pipefail && xcodebuild clean test                            \
  -project Portal.xcodeproj                                         \
  -scheme Portal                                                    \
  -sdk iphonesimulator                                              \
  -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'     \
  -derivedDataPath './output'                                       \
  OTHER_SWIFT_FLAGS='-Xfrontend -debug-time-function-bodies'        \
  | tee ./output/xcodebuild_build_raw.log                           \
  | xcpretty -f `xcpretty-json-formatter`


bundle exec danger
