#!/bin/bash

set -e
set -x

# Install environment dependencies
# proselint is a dependency needed by danger-prose plugin.
pip install proselint

# Install gems and run danger
bundle install
bundle exec danger
